name: wireguard-gui
base: core22
version: '0.1.1'
summary: Wireguard client GUI made with nextauri
icon: src-tauri/icons/128x128.png
description: |
  Provide a Wireguard client GUI for easy profile management
grade: stable
confinement: strict
architectures:
  - build-on: amd64

apps:
  wireguard-gui:
    command: usr/bin/wireguard-gui
    common-id: com.wireguard-gui.gg
    extensions: [gnome]
    desktop: usr/share/applications/wireguard-gui.desktop
    plugs:
      - home
      - network
      - network-manager
      - network-control
      - modem-manager
      - network-setup-observe
      - firewall-control
      - hardware-observe
      - network-setup-control
      - login-session-observe
      - network-observe
      - system-observe # Added for additional diagnostics

parts:
  sudoers:
    plugin: dump
    source: etc/sudoers.d
    source-type: local
    organize:
      snap_sudoers: etc/sudoers.d/snap_sudoers

  wireguard-gui:
    plugin: nil
    override-build: |
      wget https://github.com/leon3s/wireguard-gui/releases/download/0.1.1-stable/wireguard-gui_0.1.1_amd64.deb
      dpkg -x wireguard-gui_0.1.1_amd64.deb $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - dpkg
      - wget
    stage-packages:
      - libudev1
      - sudo
      - pkexec
      - wireguard-tools
      - zenity
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man

# Mount webkit2gtk-4
layout:
  /usr/libexec/sudo:
    bind: $SNAP/usr/libexec/sudo
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/lib/NetworkManager:
    bind: $SNAP/usr/lib/NetworkManager
  /etc/NetworkManager:
    bind: $SNAP_DATA/conf
  /var/lib/NetworkManager:
    bind: $SNAP_DATA/var/lib/NetworkManager
